name: Codecov Coverage (Client)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecov:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Type Check (TypeScript)
        run: npx tsc --noEmit

      - name: Security Audit (npm audit)
        run: npm audit --audit-level=moderate

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Run tests with coverage
        run: npx jest --coverage --runInBand

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: client
          name: codecov-client
          fail_ci_if_error: true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
